
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "GlobalWeather", targetNamespace = "http://www.webserviceX.NET", wsdlLocation = "http://www.webservicex.net/globalweather.asmx?WSDL")
public class GlobalWeather
    extends Service
{

    private final static URL GLOBALWEATHER_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://www.webservicex.net/globalweather.asmx?WSDL");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        GLOBALWEATHER_WSDL_LOCATION = url;
    }

    public GlobalWeather(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GlobalWeather() {
        super(GLOBALWEATHER_WSDL_LOCATION, new QName("http://www.webserviceX.NET", "GlobalWeather"));
    }

    /**
     * 
     * @return
     *     returns GlobalWeatherSoap
     */
    @WebEndpoint(name = "GlobalWeatherSoap")
    public GlobalWeatherSoap getGlobalWeatherSoap() {
        return (GlobalWeatherSoap)super.getPort(new QName("http://www.webserviceX.NET", "GlobalWeatherSoap"), GlobalWeatherSoap.class);
    }

}
